Update GitHub Actions workflow

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -1,12 +1,10 @@
 name: Build and Deploy
 
 on:
-  repository_dispatch:
-    types: [trigger-build]
   push:
-    branches:
-      - main
+    branches: [ "main", "staging" ]
   pull_request:
+    branches: [ "main", "staging" ]
   workflow_dispatch:
 
 env:
@@ -14,6 +12,8 @@ env:
 
 jobs:
   build:
+    # Only run if not a Dependabot PR
+    if: ${{ github.actor != 'dependabot[bot]' }}
     runs-on: ubuntu-22.04
     permissions:
       id-token: write
@@ -47,7 +47,7 @@ jobs:
         sudo apt-get install -y docker.io
 
     - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v1
+      uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
         aws-region: ${{ secrets.AWS_REGION }}
@@ -69,119 +69,44 @@ jobs:
         echo "Using CACHE_VERSION:"
         echo "${{ steps.cache-version.outputs.version }}"
 
+    - name: Set IMAGE_TAG
+      id: image_tag
+      shell: bash
+      run: |
+        # Determine the branch name based on the event type
+        if [ "${{ github.event_name }}" == "pull_request" ]; then
+          # For pull requests, use the base branch (target branch)
+          BRANCH_NAME="${{ github.event.pull_request.base.ref }}"
+        else
+          # For pushes, use the ref name
+          BRANCH_NAME="${{ github.ref_name }}"
+        fi
+
+        echo "BRANCH_NAME is: $BRANCH_NAME"
+
+        # Ensure BRANCH_NAME is either 'main' or 'staging'
+        if [ "$BRANCH_NAME" != "main" ] && [ "$BRANCH_NAME" != "staging" ]; then
+          echo "Error: BRANCH_NAME must be 'main' or 'staging'. Got '$BRANCH_NAME'"
+          exit 1
+        fi
+
+        # Construct the IMAGE_TAG
+        IMAGE_TAG="${{ github.sha }}-$BRANCH_NAME"
+
+        echo "IMAGE_TAG is: $IMAGE_TAG"
+
+        # Set the output variable
+        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
+
     - name: Build, tag, and push docker image to Amazon ECR
       env:
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        REPOSITORY: ${{ secrets.ECR_REPO_NAME }} 
-        IMAGE_TAG: ${{ github.sha }}
+        REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
+        IMAGE_TAG: ${{ steps.image_tag.outputs.image_tag }}
+        OPENAI_SECRET_NAME: ${{ secrets.OPENAI_SECRET_NAME }}
+        FLASK_SECRET_NAME: ${{ secrets.FLASK_SECRET_NAME }}
+        REGION: ${{ secrets.AWS_REGION }}
       run: |
-        docker build --build-arg OPENAI_SECRET_NAME=${{ secrets.OPENAI_SECRET_NAME }} --build-arg FLASK_SECRET_NAME=${{ secrets.FLASK_SECRET_NAME }} --build-arg CACHE_VERSION=${{ steps.cache-version.outputs.version }} --build-arg REGION=${{secrets.AWS_REGION}} -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
+        echo "Using IMAGE_TAG: $IMAGE_TAG"
+        docker build --build-arg OPENAI_SECRET_NAME=${OPENAI_SECRET_NAME} --build-arg FLASK_SECRET_NAME=${FLASK_SECRET_NAME} --build-arg CACHE_VERSION=${{ steps.cache-version.outputs.version }} --build-arg REGION=${{secrets.AWS_REGION}} -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
         docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
-
-    - name: Update Terraform Cloud Variable in destination workspace - Production
-      if: github.event_name == 'pull_request' && github.base_ref == 'main' || github.event_name == 'push' && github.ref == 'refs/heads/main'
-      run: |
-        curl \
-          --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
-          --header "Content-Type: application/vnd.api+json" \
-          --request PATCH \
-          --data '{
-            "data": {
-              "id": "${{ secrets.CONTAINER_LABEL_AIDEMO_VARIABLE_ID }}",
-              "type": "vars",
-              "attributes": {
-                "value": "${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}"
-              }
-            }
-          }' \
-        https://app.terraform.io/api/v2/workspaces/${{ secrets.CONTAINER_LABEL_AIDEMO_WORKSPACE_ID }}/vars/${{ secrets.CONTAINER_LABEL_AIDEMO_VARIABLE_ID }}
-
-    - name: Update Terraform Cloud Variable in destination workspace - Staging
-      if: github.event_name == 'pull_request' && github.base_ref == 'staging' || github.event_name == 'push' && github.ref == 'refs/heads/staging'
-      run: |
-        curl \
-          --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
-          --header "Content-Type: application/vnd.api+json" \
-          --request PATCH \
-          --data '{
-            "data": {
-              "id": "${{ secrets.CONTAINER_LABEL_AIDEMO_VARIABLE_ID }}",
-              "type": "vars",
-              "attributes": {
-                "value": "${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}"
-              }
-            }
-          }' \
-        https://app.terraform.io/api/v2/workspaces/${{ secrets.CONTAINER_LABEL_AIDEMO_WORKSPACE_ID_STAGING }}/vars/${{ secrets.CONTAINER_LABEL_AIDEMO_VARIABLE_ID }}
-
-    - name: Update Source workspace Terraform Cloud Variable
-      if: github.event_name == 'pull_request' && (github.base_ref == 'main' || github.base_ref == 'staging') || github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging')
-      run: |
-        curl \
-          --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
-          --header "Content-Type: application/vnd.api+json" \
-          --request PATCH \
-          --data '{
-            "data": {
-              "id": "${{ secrets.source_workspace_flaskai_variable_id }}",
-              "type": "vars",
-              "attributes": {
-                "value": "${{ secrets.ECR_REPO_NAME }}:${{ github.sha }}"
-              }
-            }
-          }' \
-        https://app.terraform.io/api/v2/workspaces/${{ secrets.source_workspace_id_flaskai }}/vars/${{ secrets.source_workspace_flaskai_variable_id }}
-
-    - name: Trigger Terraform Cloud Run - Production
-      if: github.event_name == 'pull_request' && github.base_ref == 'main' || github.event_name == 'push' && github.ref == 'refs/heads/main'
-      run: |
-        curl \
-          --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
-          --header "Content-Type: application/vnd.api+json" \
-          --request POST \
-          --data '{
-            "data": {
-              "attributes": {
-                "is-destroy":false,
-                "message":"Triggered from GitHub Actions"
-              },
-              "type":"runs",
-              "relationships": {
-                "workspace": {
-                  "data": {
-                    "type":"workspaces",
-                    "id":"${{ secrets.container_label_aidemo_workspace_id}}"
-                  }
-                }
-              }
-            }
-          }' \
-          https://app.terraform.io/api/v2/runs
-
-    - name: Trigger Terraform Cloud Run - Staging
-      if: github.event_name == 'pull_request' && github.base_ref == 'staging' || github.event_name == 'push' && github.ref == 'refs/heads/staging'
-      run: |
-        curl \
-          --header "Authorization: Bearer ${{ secrets.TFC_TOKEN }}" \
-          --header "Content-Type: application/vnd.api+json" \
-          --request POST \
-          --data '{
-            "data": {
-              "attributes": {
-                "is-destroy":false,
-                "message":"Triggered from GitHub Actions"
-              },
-              "type":"runs",
-              "relationships": {
-                "workspace": {
-                  "data": {
-                    "type":"workspaces",
-                    "id":"${{ secrets.CONTAINER_LABEL_AIDEMO_WORKSPACE_ID_STAGING }}"
-                  }
-                }
-              }
-            }
-          }' \
-          https://app.terraform.io/api/v2/runs
-
-
